name: Sonarqube Analysis

env:
  NET_VERSION: '7.x'
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_HOST: https://sonarcloud.io
  SONAR_ORGANIZATION: maurosoft1973
  SONAR_PROJECT: maurosoft1973_FileSystem

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
  use-container:
    runs-on: ubuntu-latest
    container: maurosoft1973/alpine-net-sonarqube-scanner
    steps:
      - name: Run in container
        run: | # Example
          env
          ls -la
          /scripts/run-alpine-sonarqube-scanner.sh

  quality:
    name: Sonarqube Analysis
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@v3
         with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

       - name: Run the build process with Docker
         uses: addnab/docker-run-action@v3
         with:
           image: maurosoft1973/alpine-net-sonarqube-scanner
           options: -v ${{ github.workspace }}:/source
           run: |
             /scripts/run-alpine-sonarqube-scanner.sh
             export DOTNET_ROOT=/root/.dotnet
             export PATH=$PATH:$DOTNET_ROOT:/scripts
             env
             cd /source
             dotnet --info
  