name: Sonarqube Analysis

env:
  NET_VERSION: '7.x'
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_HOST: https://sonarcloud.io
  SONAR_ORGANIZATION: maurosoft1973
  SONAR_PROJECT: maurosoft1973_FileSystem

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
  quality:
    name: Sonarqube Analysis
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@v3
         with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

       - name: Run Analysis
         uses: addnab/docker-run-action@v3
         with:
           image: maurosoft1973/alpine-net-sonarqube-scanner
           options: -v ${{ github.workspace }}:/source
           run: |
             export DOTNET_ROOT=/root/.dotnet
             export PATH=$PATH:$DOTNET_ROOT:/scripts
             dotnet sonarscanner begin /o:"${{ env.SONAR_ORGANIZATION }}" /k:"${{ env.SONAR_PROJECT }}" /d:sonar.token="${{ env.SONAR_TOKEN }}" /d:sonar.host.url="${{ env.SONAR_HOST }}" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
             dotnet build --no-incremental
             dotnet-coverage collect 'dotnet test' -f xml  -o 'coverage.xml'
             dotnet sonarscanner end /d:sonar.login="${{ env.SONAR_TOKEN }}"

  