name: Sonarqube Analysis

env:
  NET_VERSION: '7.x'
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_HOST: https://sonarcloud.io
  SONAR_ORGANIZATION: maurosoft1973
  SONAR_PROJECT: maurosoft1973_FileSystem

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
  use-container:
    runs-on: ubuntu-latest
    container: maurosoft1973/alpine-net-sonarqube-scanner
    steps:
      - name: Run in container
        run: | # Example
          env
          ls -la
          /scripts/run-alpine-sonarqube-scanner.sh

  quality:
    name: Sonarqube Analysis
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@v3
         with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

       - name: Run the build process with Docker
         uses: addnab/docker-run-action@v3
         with:
           image: maurosoft1973/alpine-net-sonarqube-scanner
           options: -v ${{ github.workspace }}:/source
           run: |
             env
             /scripts/run-alpine-sonarqube-scanner.sh
             /root/.dotnet/dotnet sonarscanner begin /o:"${{ env.SONAR_ORGANIZATION }}" /k:"${{ env.SONAR_PROJECT }}" /d:sonar.login="${{ env.SONAR_TOKEN }}" /d:sonar.host.url="${{ env.SONAR_HOST }}" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
             /root/.dotnet/dotnet build --no-incremental
             /root/.dotnet/dotnet-coverage collect 'dotnet test' -f xml  -o 'coverage.xml'
             /root/.dotnet/dotnet sonarscanner end /d:sonar.login="${{ env.SONAR_TOKEN }}"
  